---
title: "README_Scripts"
author: "Gayathri Nagarajan"
date: "4/28/2020"
output: html_document
---
This is the ReadMe file for project for course "Getting and cleaning data".

The script is titled "run_analysis.R" that does the following :

1. Merges the training and the test sets to create one data set.
2.Extracts only the measurements( columns) on the mean and standard deviation for each measurement from this data set in #1.
3. Uses descriptive activity names to name the activities in the data set
4 Appropriately labels the data set with descriptive variable names.
5 From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject
6.The end result is shown in a file called "final_clean_set.csv"

The final result is a wide format containing 180 rows ( one row for each subject and activity performed by the subject ).
The total number of rows ( 30 subjects * 6 activities= 180). The total number of columns is 81 ( 81 observations containing mean of the variable/observation) for each subject/activity.

The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:




http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Data for this project was downloaded from :
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

How to get the output for this project :

1. Download the data set from the link above 
2.Create a Scripts folder and place run_analysis.R script 
3.Run source("run_analysis.R"), then it will generate a new file final_clean_set.txt in your working directory.